### ISSUE TITLE
How to implement manufacturer and so on?

### ISSUE THREAD

**Issue by lovekull76** [alexbarcelo/hass-mqtt-things#1]
Hi,

Using your excellent module for many things but I would like to "brand" the device in HASS with "manufacturer" and so on. I see that you have implemented optional parameters but I can't figure out how to use them (pass them as params to add_things :/

And one more thing, do you have plans for a binary_sensor as well? Would be great!

Best regards, L

**Comment by alexbarcelo** [comment]
Manufacturer and model can now be easily set in v0.5.3; this release also has `binary_sensor`. See the release notes for more info and a link to an example. I hope it helps!

**Comment by lovekull76** [comment]
Great! Branding works great! Will check out the binary_sensor as well!
Thank you for your great work!
